apiVersion: apps/v1
kind: Deployment
metadata:
  name: dofexam-app1-200036973-deploy
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: dofexam-app1-200036973
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: dofexam-app1-200036973
    spec:
      containers:
      - name: app-cont
        image: hotval/dofexam-app1-200036973:%IMAGE-PLACEHOLDER%
        ports:
        - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: dofexam-app1-200036973-svc
  labels:
    app: dofexam-app1-200036973
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 31000
    protocol: TCP
  selector:
    app: dofexam-app1-200036973
